# Generated by Django 3.1.6 on 2023-11-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_img', models.ImageField(upload_to='company_images/')),
                ('total_grade', models.CharField(max_length=10)),
                ('social_grade', models.CharField(max_length=10)),
                ('env_grade', models.CharField(max_length=10)),
                ('gov_grade', models.CharField(max_length=10)),
                ('profit', models.FloatField()),
                ('revenue', models.FloatField()),
                ('stock', models.ImageField(upload_to='company_stock_images/')),
                ('industry', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
            ],
        ),
    ]
